# Generated by Django 6.0.2 on 2026-02-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='tenants_ten_domain_a84b8d_idx'), models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('PRIMARY_COLOR', 'Primary Color'), ('LOGO_URL', 'Logo URL'), ('MAX_SHIPMENT_WEIGHT', 'Max Shipment Weight'), ('AUTO_ASSIGN_DRIVER', 'Auto Assign Driver')], max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'key'], name='tenants_ten_tenant__7658f2_idx')],
                'unique_together': {('tenant', 'key')},
            },
        ),
    ]
