# Generated by Django 6.0.2 on 2026-02-24 07:31logesticteam

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('RTO', 'RTO'), ('Delivery Failed', 'Delivery Failed')], default='Created', max_length=30)),
                ('is_reverse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
 logesticteam
        ),
    ]
