# Generated by Django 6.0.2 on 2026-02-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("SHIPMENT_ASSIGNED", "Shipment Assigned"),
                    ("DELIVERY_UPDATE", "Delivery Status Update"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PAYOUT_PROCESSED", "Payout Processed"),
                ],
                max_length=50,
            ),
        ),
    ]
